DROP TABLE USERS IF EXISTS;
CREATE TABLE USERS (
  id INT(11) NOT NULL PRIMARY KEY auto_increment,
  login VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  job VARCHAR(100) NULL
);

DROP TABLE TODO IF EXISTS;
CREATE TABLE TODO (
  id INT(11) NOT NULL PRIMARY KEY auto_increment,
  text VARCHAR(255) NOT NULL,
  id_user INT(11) NOT NULL,
);

ALTER TABLE TODO ADD CONSTRAINT FK_TODO_USER FOREIGN KEY (id_user) REFERENCES USERS(id);